import { IPv4Result } from "./ipv4";
import { IPv6Result } from "./ipv6";
import { VLSMSubnet } from "./ipv4";

export function generateIPv4Report(result: IPv4Result): string {
  if (!result.isValid) return "Invalid IP Address or CIDR notation.";

  return `
═══════════════════════════════════════════════════════
  SMART IP SUBNET CALCULATOR & ANALYZER - REPORT
═══════════════════════════════════════════════════════

  IPv4 SUBNET CALCULATION REPORT
───────────────────────────────────────────────────────

  INPUT
  IP Address:          ${result.ip}
  CIDR Notation:       /${result.cidr}

  NETWORK IDENTITY
  IP Class:            ${result.ipClass}
  IP Type:             ${result.ipType}
  Network ID:          ${result.networkId}
  Broadcast Address:   ${result.broadcastAddress}

  ADDRESSING
  Subnet Mask:         ${result.subnetMask}
  Wildcard Mask:       ${result.wildcardMask}
  First Usable IP:     ${result.firstUsable}
  Last Usable IP:      ${result.lastUsable}

  CAPACITY
  Total IP Addresses:  ${result.totalIPs.toLocaleString()}
  Usable Hosts:        ${result.usableHosts.toLocaleString()}
  Network Bits:        ${result.networkBits}
  Host Bits:           ${result.hostBits}

  BINARY REPRESENTATION
  ${result.binary}

───────────────────────────────────────────────────────
  Generated by Smart IP Subnet Calculator & Analyzer
  Date: ${new Date().toISOString()}
═══════════════════════════════════════════════════════
`.trim();
}

export function generateIPv6Report(result: IPv6Result): string {
  if (!result.isValid) return "Invalid IPv6 Address or CIDR notation.";

  return `
═══════════════════════════════════════════════════════
  SMART IP SUBNET CALCULATOR & ANALYZER - REPORT
═══════════════════════════════════════════════════════

  IPv6 SUBNET CALCULATION REPORT
───────────────────────────────────────────────────────

  INPUT
  IPv6 Address:        ${result.address}
  CIDR Notation:       /${result.cidr}

  DETAILS
  Expanded Form:       ${result.expanded}
  Compressed Form:     ${result.compressed}
  Network Prefix:      ${result.networkPrefix}
  IP Type:             ${result.ipType}

  RANGE
  First Address:       ${result.firstAddress}
  Last Address:        ${result.lastAddress}
  Total Addresses:     ${result.totalAddresses}

───────────────────────────────────────────────────────
  Generated by Smart IP Subnet Calculator & Analyzer
  Date: ${new Date().toISOString()}
═══════════════════════════════════════════════════════
`.trim();
}

export function generateVLSMReport(subnets: VLSMSubnet[], baseNetwork: string, baseCidr: number): string {
  const rows = subnets.map((s, i) =>
    `  ${(i + 1).toString().padEnd(4)} ${s.name.padEnd(16)} ${s.neededHosts.toString().padEnd(8)} /${s.cidr.toString().padEnd(4)} ${s.networkAddress.padEnd(18)} ${s.broadcastAddress.padEnd(18)} ${s.subnetMask}`
  ).join("\n");

  return `
═══════════════════════════════════════════════════════
  VLSM SUBNET ALLOCATION REPORT
═══════════════════════════════════════════════════════

  Base Network: ${baseNetwork}/${baseCidr}

  ${"#".padEnd(4)} ${"Subnet".padEnd(16)} ${"Hosts".padEnd(8)} ${"CIDR".padEnd(5)} ${"Network".padEnd(18)} ${"Broadcast".padEnd(18)} Mask
───────────────────────────────────────────────────────
${rows}
───────────────────────────────────────────────────────
  Generated: ${new Date().toISOString()}
═══════════════════════════════════════════════════════
`.trim();
}

export function downloadAsFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadCSV(ips: string[], filename: string) {
  const content = "IP Address\n" + ips.join("\n");
  const blob = new Blob([content], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
